# -*- coding: utf-8 -*-
"""Study Case DA_Game Sales.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N80O3yaHKXoTZVymH2ZAzGWzc5T0OMjH

Gaming industry is an interesting field to explore, it would be fun knowing who the most popular publishers and developers are and which games are the most popular, so let's analyze!
"""

from google.colab import drive
drive.mount('/content/drive')

"""Import library"""

import pandas as pd
import numpy as np

"""Reading dataset"""

Game_Sales = pd.read_csv('/content/drive/MyDrive/RevoU/Games Sales - Case Study - Games.csv')
Game_Sales

Game_Sales.info()

"""After checking, it was found that there were:
1. Null
2. Incorrect data type

## 1. Null
"""

Game_Sales.isna().sum()

Game_Sales[Game_Sales['Series'].isna()]

Game_Sales_without_null = Game_Sales[~Game_Sales['Series'].isna()]
Game_Sales_without_null

Game_Sales_without_null.info()

Game_Sales_without_null['Release']

Game_Sales_without_null['Release'] = pd.to_datetime(Game_Sales_without_null['Release'], format='%m/%d/%Y')
Game_Sales_without_null['Release']

Game_Sales_without_null.info()

"""Check for duplicate data"""

duplicate = Game_Sales_without_null.duplicated()
duplicate.value_counts()

"""There are 2 duplicate data, so delete"""

Game_Sales_without_null = Game_Sales_without_null.drop_duplicates()
Game_Sales_without_null

Game_Sales_without_null.isnull().sum()

import matplotlib.pyplot as plt #import library
#check outlier using box plot
fig = plt.figure(figsize=(15,10))
ax = plt.subplot2grid((3,3), (0,0))
Game_Sales_without_null['Sales'].plot(ax=ax, kind='box', grid=True, color='tab:red')

Game_Sales_without_null['Sales'].describe()

"""Convert dot (.) to comma (,) in value of 'Sales' for export to excel/sheet"""

x = Game_Sales_without_null['Sales']
y = str(x)
z = y.replace("." , ",")
print(z)

Game_Sales_without_null.to_csv('/content/drive/MyDrive/RevoU/Game_Sales_new.csv', index=False)